find_path(LEVELDB_INCLUDE_DIR NAMES leveldb/db.h)
find_library(LEVELDB_LIBRARY NAMES libleveldb.a libleveldb.lib)

find_library(SNAPPY_LIBRARY snappy)
find_path(SNAPPY_INCLUDE_DIR snappy.h PATH_SUFFIXES snappy)

if(LEVELDB_INCLUDE_DIR AND LEVELDB_LIBRARY AND SNAPPY_LIBRARY AND SNAPPY_INCLUDE_DIR)
  set(LEVELDB_INCLUDE_DIR ${LEVELDB_INCLUDE_DIR} ${SNAPPY_INCLUDE_DIR})
  set(LEVELDB_LIBRARY ${LEVELDB_LIBRARY} ${SNAPPY_LIBRARY})
  set(LevelDB_FOUND TRUE)
endif(LEVELDB_INCLUDE_DIR AND LEVELDB_LIBRARY AND SNAPPY_LIBRARY AND SNAPPY_INCLUDE_DIR)


